language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "qzWNCpZUVo9txahKZfyvmIeXbQYR9U6KnU+y43RH2jhghKzEgecQwqF8GOWv3QG+ns2CwWYKhJDw582ksnxIDWrM6LiFho0OoNZJwRcyHM8TcuUyUoOVRh1RJf+sMb+jCS7D4etP/pNiX2btZVOtmN2fDJZxEjyx9RqvQhhlPShoTFXrDYzC42eAcVfBsX5ivh2mtwMnY2eobPmQ8xDavbVaOvwZTgIOOtRHErxjTeUm34ajUes+8Fdn9ggzpTsw7Fpm5foa+/S3Jgzw+E33Vp5Ym/0M0+323xU1xmsKqpW1Rc5ViiROHw2dDrKtRzzI7dULbkE3VV4aX5Kf/4+nHoL/ASLDWB3Ra6Brx8R7MBMb0wd0UFHyx1njCMqpeqke0d+85lcmXc/YPn5Jcokzd+s3+Au6wL0QHej1PAaecXjdZAVT+3dGYbSVGK0DzgS3WZ7U1apIipxZFN1uHlJTLxGdffcGT9da/ytrck7ATxEH0Q0jtoKtxGKYfB1i1QV3mbmtSM1Yhdk6E9dL9tpe3ra0IlMWs1LrncL26j/nEieEStTty1akK6V7HJGq6Z/VHnhv5n0ZWir18/sMaKGU03xYLcnJCbBkq1QqQ5lg3kr44xEdCEEpCcOg0qyO9Hgm5teBu8zerQ7ET+9CHICegBYQRIXpT8ZyTJa0we4Q1eA="
